# Generated by Django 4.1.4 on 2023-01-03 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_note', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fuel/Gas', 'Fuel/Gas'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=200)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=200)),
                ('is_bill_splitted', models.BooleanField(default=False)),
                ('transaction_created', models.DateTimeField(auto_now=True)),
                ('transaction_updated', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payer', to=settings.AUTH_USER_MODEL)),
                ('transc_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transc_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitBillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_paid', models.BooleanField(default=False)),
                ('bill_paid_on', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('transac_bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.transactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(null=True)),
                ('expense', models.FloatField(null=True)),
                ('budget', models.FloatField(null=True)),
                ('owe_balance', models.FloatField(null=True)),
                ('credit_balance', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
