# Generated by Django 4.1.4 on 2023-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expense',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owe_balance',
            field=models.FloatField(default=0),
        ),
    ]
