# Generated by Django 4.1.4 on 2023-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_profile_budget_alter_profile_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitbillmodel',
            name='bill_amount',
            field=models.FloatField(default=0),
        ),
    ]
