# Generated by Django 4.1.4 on 2023-01-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_splitbillmodel_bill_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitbillmodel',
            name='bill_paid_on',
        ),
    ]
