# Generated by Django 4.1.4 on 2023-01-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0004_remove_splitbillmodel_bill_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='total_split',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
