# Generated by Django 4.1.4 on 2023-01-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_rename_total_split_transactionmodel_totalfriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='totalfriend',
            field=models.IntegerField(default=0),
        ),
    ]
