# Generated by Django 4.1.4 on 2023-01-05 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_transactionmodel_totalfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitbillmodel',
            name='bill_paid_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='splitbillmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
