# Generated by Django 4.1.4 on 2023-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_splitbillmodel_bill_paid_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitbillmodel',
            name='bill_paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
